name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref != 'refs/heads/main')
    name: Build Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o netlogger-linux ./cmd/netlogger

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o netlogger-windows.exe ./cmd/netlogger

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: netlogger-binaries
          path: |
            netlogger-linux
            netlogger-windows.exe

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Tag
        id: tag
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: netlogger-binaries
