name: Release

env:
  GO_VERSION: ${{ vars.GO_VERSION }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: GoReleaser release
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref != 'refs/heads/main')
    name: Build Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o netlogger-linux ./cmd/netlogger

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o netlogger-windows.exe ./cmd/netlogger

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: netlogger-binaries
          path: |
            netlogger-linux
            netlogger-windows.exe
