name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  build:
    name: Build Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o netlogger-linux ./cmd/netlogger

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o netlogger-windows.exe ./cmd/netlogger

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: netlogger-binaries
          path: |
            netlogger-linux
            netlogger-windows.exe
