name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  create:
    tags:
      - '*'  # Trigger on any tag creation

permissions:
  contents: write

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o netlogger-linux ./cmd/netlogger

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o netlogger-windows.exe ./cmd/netlogger

      - name: Upload binaries
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: netlogger-binaries
          path: |
            netlogger-linux
            netlogger-windows.exe

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Tag
        id: tag
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: netlogger-binaries

      - name: Publish Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          release_name: Release ${{ steps.tag.outputs.new_tag }}
          body: |
            Automated release for tag ${{ steps.tag.outputs.new_tag }}.
          draft: false
          prerelease: false
          assets: |
            netlogger-linux
            netlogger-windows.exe
